baseurl = "https://sungodmediagroup.com/"
languageCode = "en-us"
title = "Sun God Media"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Awesome description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Sun God Media"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "<div style='color:#f05f40'>Result Driven Marketing</div>"
		subtitle   = "We Bring New Customers to Your Business!"
		buttonText = "Get More Customers"


	# About section
	[params.about]
		headline    = "More Customers | Measurable Results | Proven ROI"
		description = "We specialize in bringing new customers to your business. We are a boutique marketing and media company with a passion for helping your business grow! We focus on data driven and ROI focused marketing."
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Relationships Matter"
            description = "We believe strongly in building a long term relationship with our clients."

        [[params.services.list]]
      			icon = "fa-money"
      			title = "Measurable ROI"
      			description = "Do you know the ROI of your marketing? Our focus on marketing that can be tracked and measured."

		[[params.services.list]]
            icon = "fa-line-chart"
            title = "Grow Your Business"
            description = "We take pride in growing your business! Are you ready for an influx of customers?"

        [[params.services.list]]
            icon = "fa-heart"
            title = "We Love Our Job"
            description = "Let us focus on bringing you more customers! So you can focus on your passion."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = ""

		# [params.aside.button]
		# 	text = "Download now"
		# 	link = "//github.com/digitalcraftsman/hugo-creative-theme"
    #
	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to get started, get new customers and grow your business? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "service@sungodmediagroup.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
